"""
L0Learn with non-negative box constraints for underdetermined system.

NOTE: well, it's not working too well with just L0. Perhaps some L2 can
Regularize the system enough to get it to work
"""

import numpy as np
import l0learn

# Problem size and random seed
Q = 50            # number of targets/samples
N = 50_000        # number of households/features  
rng = np.random.default_rng(0)

# Metric matrix M (shape Q x N) - underdetermined system
M = rng.normal(size=(Q, N))

# Target vector y
y = np.random.lognormal(mean=10, sigma=2, size=50).round()

print("=== Underdetermined System with L0Learn ===")
print(f"Original M shape: {M.shape}")
print(f"Target sum: {y.sum():,.0f}")

# Nah man, we're running the whole thing 
M_subset = M

# Convert to proper format
M_fortran = np.asfortranarray(M_subset).astype(np.float64)
y_fortran = y.astype(np.float64)

# Fit with L0 and non-negative constraints

fit = l0learn.fit(
    X=M_fortran,
    y=y_fortran,
    penalty="L0",
    max_support_size=100,  # At most 1000 non-zero
    lows=0.0,  # Non-negative constraint
    highs=float('inf'),
    intercept=False,
    num_lambda=50  # Need this 50 or under or it will segfault
)


w = fit.coeff(lambda_0= 0.000016, include_intercept=False)
y_hat = M_subset @ w

y[1:5]
y_hat[1:5]

# NOTE: Other generated by Claude Code for when gamma was involved
solutions = []
for gamma_idx, gamma in enumerate(fit.gamma):
    lambdas = fit.lambda_0[gamma_idx]
    
    for lam in lambdas:
        w = fit.coeff(lambda_0=lam, gamma=gamma, include_intercept=False)
        if hasattr(w, 'toarray'):
            w = w.toarray().flatten()
        else:
            w = np.asarray(w).flatten()
        
        nnz = np.sum(w > 1e-10)
        if nnz == 0:
            continue
            
        y_hat = M_subset @ w
        error = np.linalg.norm(y - y_hat)
        
        solutions.append({
            'gamma': gamma,
            'lambda': lam,
            'nnz': nnz,
            'error': error,
            'weights': w
        })

if solutions:
    # Sort by error
    solutions.sort(key=lambda x: x['error'])
    
    print("\n=== Top Solutions ===")
    print(f"{'NNZ':<6} {'Error':<12} {'Gamma':<10} {'Lambda'}")
    print("-" * 45)
    
    for sol in solutions[:10]:
        print(f"{sol['nnz']:<6} {sol['error']:<12.2f} {sol['gamma']:<10.2e} {sol['lambda']:.6f}")
    
    # Best solution
    best = solutions[0]
    print(f"\n=== Best Solution ===")
    print(f"Non-zero weights: {best['nnz']}")
    print(f"All weights >= 0: {np.all(best['weights'] >= -1e-10)}")
    
    if best['nnz'] > 0:
        positive_weights = best['weights'][best['weights'] > 1e-10]
        print(f"Weight range: [{positive_weights.min():.6f}, {positive_weights.max():.6f}]")
    
    print(f"Reconstruction error: {best['error']:.2f}")
    
    # Map back to full space
    w_full = best['weights']
    
    y_hat = M @ w_full
    print(f"\nFirst 5 targets:     {y[:5]}")
    print(f"First 5 predictions: {np.round(y_hat[:5], 0)}")
    
    rel_error = best['error'] / np.linalg.norm(y) * 100
    print(f"\nRelative error: {rel_error:.2f}%")
else:
    print("\nNo non-zero solutions found.")
